apiVersion: v1
kind: Service
metadata:
  name: debezium-kafka-connect-svc
  namespace: test
  labels:
    app: debezium-kafka-connect
spec:
  type: NodePort
  selector:
   app: debezium-kafka-connect
  ports:
    - name: http
      port: 8083
      targetPort: 8083
      nodePort: 30000
