version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:1.0
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
# docker run -it --rm --name zookeeper -p 2181:2181 -p 2888:2888 -p 3888:3888 debezium/zookeeper:1.0

  kafka:
    image: debezium/kafka:1.0
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
# docker run -it --rm --name kafka -p 9092:9092 --link zookeeper:zookeeper debezium/kafka:1.0

  postgres:
    image: debezium/postgres:11
    ports:
     - 5432:5432
    environment:
     - POSTGRES_DB=debezium
     - POSTGRES_USER=user
     - POSTGRES_PASSWORD=password
# docker run -it --rm --name postgres -p 5432:5432 -e POSTGRES_PASSWORD=password -e POSTGRES_USER=user -e POSTGRES_DB=debezium debezium/postgres:11

  connect:
    image: debezium/connect:1.0
    ports:
     - 8083:8083
    links:
     - kafka
     - postgres
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - CONFIG_STORAGE_TOPIC=debezium_connect_config
     - OFFSET_STORAGE_TOPIC=debezium_connect_offset
     - STATUS_STORAGE_TOPIC=debezium_connect_status
# docker run -it --rm --name connect -p 8083:8083 -e CONFIG_STORAGE_TOPIC=debezium_connect_config -e OFFSET_STORAGE_TOPIC=debezium_connect_offset -e STATUS_STORAGE_TOPIC=debezium_connect_status --link zookeeper:zookeeper --link kafka:kafka --link postgres:postgres debezium/connect:1.0



